require('my-plugins')
require('my-plugins/settings')
require('my-settings')
require('my-nvim-cmp')
require('my-themes/nightfox')
require('my-lsp')
require('my-treesitter')
require('my-treesitter/context')
require('my-treesitter/rainbow')
require('my-plugins/lualine')
require('my-mappings')
require('my-telescope')

-- Set theme
vim.cmd("colorscheme nordfox")
